modLoader="javafml"
loaderVersion="[30,)"
license="All Rights Reserved"

#issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]]
modId="wtbw_tools"
version="${file.jarVersion}"
displayName="WTBW Tools"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="tools.png"
#credits="Thanks for this wtbw mod goes to Java" #optional
authors="Naxanria, Sunekaer"
description='''
Adds new tools
'''
[[dependencies.wtbw_tools]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wtbw_tools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wtbw_tools]]
    modId="wtbw_lib"
    mandatory=true
    versionRange="[2.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.wtbw_tools]]
    modId="wtbw_core"
    mandatory=true
    versionRange="[2.0,)"
    ordering="AFTER"
    side="BOTH"