modLoader="javafml"
loaderVersion="[30,)"

#issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]]
modId="wtbw_tools"
version="${file.jarVersion}"
displayName="WTBW Tools"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="tools.png"
#credits="Thanks for this wtbw mod goes to Java" #optional
authors="Naxanria, Sunekaer"
description='''
Adds new tools
'''
[[dependencies.wtbw_tools]]
    modId="forge"
    mandatory=true
    versionRange="[30.0.30,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wtbw_tools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wtbw_tools]]
    modId="wtbw_lib"
    mandatory=true
    versionRange="[1.0.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wtbw_tools]]
    modId="wtbw_core"
    mandatory=true
    versionRange="[1.0.5,)"
    ordering="NONE"
    side="BOTH"